AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  my-lambda-php

  Sample SAM Template for my-lambda-php

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration:
        Type: REGIONAL
      StageName: Prod
      TracingEnabled: True
      BinaryMediaTypes:
        - '*~1*'
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      PackageType: Image
      MemorySize: 512
      Tracing: PassThrough
      Policies:
        - CloudWatchLambdaInsightsExecutionRolePolicy # Add IAM Permission for Lambda Insight Extension
      Environment:
        Variables:
          RUST_LOG: debug
          PORT: "8080"
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /
            Method: ANY
        Proxy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /{proxy+}
            Method: ANY
    Metadata:
      DockerTag: v1
      DockerContext: ./
      Dockerfile: Dockerfile

Outputs:
  URL:
    Description: "API Gateway endpoint URL for Prod stage for PHP application"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
  Function:
    Description: "Lambda Function ARN"
    Value: !GetAtt Function.Arn
